# This is a basic workflow to help you get started with Actions

name: org-audit action
on: workflow_dispatch

jobs:

  audit_log:
    runs-on: ubuntu-latest
    name: Membership Audit Log
   
    steps:
    - name: Membership Audit Log Action
      uses: svanboxel/org-audit-action@master
      with:
         organization: 'krishh2512'
         token: ${{ secrets.TOKEN }}
         issue: true
         samlIdentities: true
